export const AUCTION_BUMP_LENGTH = 6
export const AUCTION_DELAY_LENGTH = 4

export const ADDRESS_LENGTH = 40
export const ALLOWED_TIMESTAMP_LENGTH = 8

export const PRIVATE_AUCTION_DEADLINE_LENGTH = 8

export const TAKER_FEE_RECEIVER_LENGTH = 40
export const TAKER_FEE_RATIO_LENGTH = 24

export const FLAGS_LENGTH = 2

export const HAS_TAKING_FEE_FLAG = 0x80
export const RESOLVERS_LENGTH_MASK = 0x78
export const RESOLVERS_LENGTH_OFFSET = 3
export const POINTS_LENGTH_MASK = 0x07

export const CONTRACT_TAKER_FEE_PRECISION = 1e9
